# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.factory.request:
      class: AppBundle\Http\RequestFactory
      arguments: ["%shop_url%", "%shop_admin_user%", "%shop_admin_password%", "@security.token_storage","@session","@cache.app"]

    api.customer.create:
      class: AppBundle\Service\CustomerCreate
      arguments: ['%shop_url%']
    api.customer.login:
      class: AppBundle\Service\CustomerLogin
      arguments: ['%shop_url%']
    api.customer.data:
      class: AppBundle\Service\CustomerData
      arguments: ['%shop_url%']

    api.catalog.categories:
      class: AppBundle\Service\Catalog\Categories
      arguments: ["%shop_url%", "%shop_admin_user%", "%shop_admin_password%", "@cache.app"]
    api.catalog.product:
      class: AppBundle\Service\Catalog\Product
      arguments: ["%shop_url%", "%shop_admin_user%", "%shop_admin_password%", "@cache.app"]
    api.checkout.cart:
      class: AppBundle\Service\Checkout\Cart
      arguments: ["@app.factory.request"]
    api.checkout.shipping:
      class: AppBundle\Service\Checkout\Shipping
      arguments: ['%shop_url%', "%shop_admin_user%", "%shop_admin_password%", "@cache.app", "@security.token_storage"]


    api.catalog.product.helper:
      class: AppBundle\Service\Catalog\ProductHelper
      arguments: ["%shop_url%", "%shop_admin_user%", "%shop_admin_password%", "@cache.app"]

    security.token.factory:
      class: AppBundle\Security\Token\MagentoTokenFactory
      arguments: ["@api.customer.login", "@api.customer.data"]
    security.authenticator.api:
      class: AppBundle\Security\Authenticator\Api
      arguments: ["@security.token.factory"]

    security.provider.customer:
      class: AppBundle\Security\Provider\CustomerProvider